const grammar={"Block 1 — The Basics":["Subject Pronouns","Verb to be: am / is / are","Possessive Adjectives","Articles: a / an","Singular and Plural Nouns","Demonstratives","Basic Adjective Position","Possessive 's"],"Block 2 — Present Simple":["Present Simple Affirmative","Present Simple Negative","Present Simple Questions","Do / Does","Question Words","Adverbs of Frequency","Basic Word Order","Have / Have Got"],"Block 3 — Places and Possession":["There is / There are","Prepositions of Place","Prepositions of Time","Object Pronouns","Possessive Pronouns","Some / Any"],"Block 4 — Actions and Ability":["Can / Can't","Can for Permission","Imperatives","Present Continuous","Present Simple vs Present Continuous"],"Block 5 — Quantity":["Countable and Uncountable Nouns","Much / Many","A Lot Of","A Few / A Little","How Much / How Many"],"Block 6 — The Past":["Was / Were","Past Simple Regular Verbs","Common Irregular Verbs","Past Simple Negative","Past Simple Questions","There Was / There Were"],"Block 7 — Comparisons":["Comparative Adjectives","Superlative Adjectives","Basic Adverbs of Manner"],"Block 8 — Future":["Be Going To","Basic Will","Would Like","Basic Offers with Shall"],"Block 9 — Connecting Ideas":["And / But / Or","Because / So","Basic Infinitive of Purpose","Common Verb + Infinitive / -ing","Articles Review","Full A1 Grammar Review"]};
const app=document.querySelector("#app");
const card=(title,sub,action,locked=false)=>`<div class="card ${locked?"locked":""}" ${action&&!locked?`onclick="${action}"`:""}><span class="pill">${sub||""}</span><h3>${title}</h3></div>`;
function home(){app.innerHTML=`<section class="hero"><span class="pill">A1 → C2</span><h1>Learn English your way ✨</h1><p>Grammar, vocabulary, speaking, listening, reading, writing and pronunciation.</p></section><div class="grid">${["A1","A2","B1","B2","C1","C2"].map((x,i)=>card(x,i===0?"Start here":"Coming soon",i===0?"location.hash='a1'":"",i>0)).join("")}</div>`}
function a1(){app.innerHTML=`<button class="back" onclick="location.hash='home'">← Levels</button><section class="hero"><h1>A1 English</h1><p>Choose what you want to practice.</p></section><div class="grid">${card("Grammar","A1","location.hash='grammar'")}${card("Vocabulary","A1","location.hash='vocabulary'")}${card("Speaking","A1","location.hash='practice'")}${card("Listening","A1","location.hash='practice'")}${card("Reading","A1","location.hash='practice'")}${card("Writing","A1","location.hash='practice'")}${card("Pronunciation","A1","location.hash='practice'")}${card("Use of English","A1","location.hash='practice'")}</div>`}
function blocks(){app.innerHTML=`<button class="back" onclick="location.hash='a1'">← A1</button><section class="hero"><h1>📖 Grammar</h1><p>Choose a block.</p></section><div class="grid">${Object.keys(grammar).map((x,i)=>card(x,grammar[x].length+" topics",`location.hash='block-${i}'`)).join("")}</div>`}
function block(i){let name=Object.keys(grammar)[i],topics=grammar[name];app.innerHTML=`<button class="back" onclick="location.hash='grammar'">← Grammar</button><section class="hero"><h1>${name}</h1><p>Choose a lesson.</p></section><div class="grid">${topics.map((x,j)=>card(x,"Lesson",i===0&&j===0?"location.hash='subject-pronouns'":"alert('This lesson is next to build ✨')")).join("")}</div>`}
function subject(){app.innerHTML=`<button class="back" onclick="location.hash='block-0'">← Block 1</button><section class="hero"><span class="pill">A1 • Grammar</span><h1>Subject Pronouns</h1><p>Learn who or what does the action in a sentence.</p></section><div class="lessonbox"><h2>💡 Key idea</h2><p>A subject pronoun replaces the person, people, animal or thing that performs the action.</p><div class="pronouns">${["I","You","He","She","It","We","They"].map(x=>`<div class="pronoun">${x}</div>`).join("")}</div></div><div class="lessonbox"><h2>📚 Examples</h2><div class="example"><b>I</b> am a student.</div><div class="example"><b>She</b> is my friend.</div><div class="example"><b>They</b> are at home.</div><div class="example"><b>It</b> is a book.</div></div><div class="lessonbox"><h2>🧩 Remember</h2><p><b>I</b> = the speaker • <b>You</b> = the person/people you speak to • <b>He/She</b> = a person • <b>It</b> = a thing/animal • <b>We</b> = I + others • <b>They</b> = people/things.</p></div>`}
function simple(title){app.innerHTML=`<button class="back" onclick="location.hash='a1'">← A1</button><section class="hero"><h1>${title}</h1><p>This section is ready for the next content pass.</p></section>`}
function render(){let h=location.hash.slice(1)||"home";if(h==="home")home();else if(h==="a1")a1();else if(h==="grammar")blocks();else if(h.startsWith("block-"))block(+h.split("-")[1]);else if(h==="subject-pronouns")subject();else if(h==="vocabulary")simple("📚 Vocabulary");else if(h==="practice")simple("✏ Practice");else if(h==="progress")simple("📊 Progress");else home()}window.addEventListener("hashchange",render);render();